
import imgs from './imagenes'

const letras = [
  {
    id: 0,
    letra: "a",
    image1: imgs.auto,
    image2: imgs.avion,
    image3: imgs.arbol,
    text1: "Auto",
    text2: "Avión",
    text3: "Árbol",
  },
  {
    id: 1,
    letra: "b",
    image1: imgs.barco,
    image2: imgs.bote,
    image3: imgs.bota,
    text1: "Barco",
    text2: "Bote",
    text3: "Bota",
  },
  {
    id: 2,
    letra: "c",
    image1: imgs.casa,
    image2: imgs.caballo,
    image3: imgs.camion,
    text1: "Casa",
    text2: "Caballo",
    text3: "Camion",
  },
  {
    id: 3,
    letra: "d",
    image1: imgs.delfin,
    image2: imgs.diamante,
    image3: imgs.dinosaurio,
    text1: "Delfin",
    text2: "Diamante",
    text3: "Dinosaurio",
  },
  {
    id: 4,
    letra: "e",
    image1: imgs.elefante,
    image2: imgs.escoba,
    image3: imgs.escarapela,
    text1: "Elefante",
    text2: "Escoba",
    text3: "Escarapela",
  },
  {
    id: 5,
    letra: "f",
    image1: imgs.foca,
    image2: imgs.foco,
    image3: imgs.flor,
    text1: "Foca",
    text2: "Foco",
    text3: "Flor",
  },
  {
    id: 6,
    letra: "g",
    image1: imgs.gato,
    image2: imgs.gaviota,
    image3: imgs.gorra,
    text1: "Gato",
    text2: "Gaviota",
    text3: "Gorra",
  },
  {
    id: 7,
    letra: "h",
    image1: imgs.helado,
    image2: imgs.hielo,
    image3: imgs.hiena,
    text1: "Helado",
    text2: "Hielo",
    text3: "Hiena",
  },
  {
    id: 8,
    letra: "i",
    image1: imgs.iglesia,
    image2: imgs.iglu,
    image3: imgs.isla,
    text1: "Iglesia",
    text2: "Iglu",
    text3: "Isla",
  },
  {
    id: 9,
    letra: "j",
    image1: imgs.jirafa,
    image2: imgs.jugo,
    image3: imgs.jabali,
    text1: "Jirafa",
    text2: "Jugo",
    text3: "Jabalí",
  },
  {
    id: 10,
    letra: "k",
    image1: imgs.koala,
    image2: imgs.kiwi,
    image3: imgs.kilo,
    text1: "Koala",
    text2: "Kiwi",
    text3: "Kilo",
  },
  {
    id: 11,
    letra: "l",
    image1: imgs.leon,
    image2: imgs.libro,
    image3: imgs.luciernaga,
    text1: "León",
    text2: "Libro",
    text3: "Luciernaga",
  },
  {
    id: 12,
    letra: "m",
    image1: imgs.manzana,
    image2: imgs.murcielago,
    image3: imgs.morsa,
    text1: "Manzana",
    text2: "Murcielago",
    text3: "Morsa",
  },
  {
    id: 13,
    letra: "n",
    image1: imgs.naranja,
    image2: imgs.nutria,
    image3: imgs.nube,
    text1: "Naranja",
    text2: "Nutria",
    text3: "Nube",
  },
  {
    id: 14,
    letra: "ñ",
    image1: imgs.niandu,
    image2: imgs.nioqui,
    image3: imgs.niu,
    text1: "Ñandu",
    text2: "Ñoqui",
    text3: "Ñu",
  },
  {
    id: 15,
    letra: "o",
    image1: imgs.oso,
    image2: imgs.ola,
    image3: imgs.ovni,
    text1: "Oso",
    text2: "Ola",
    text3: "Ovni",
  },
  {
    id: 16,
    letra: "p",
    image1: imgs.perro,
    image2: imgs.pato,
    image3: imgs.pelota,
    text1: "Perro",
    text2: "Pato",
    text3: "Pelota",
  },
  {
    id: 17,
    letra: "q",
    image1: imgs.queso,
    image2: imgs.quirofano,
    image3: imgs.quimico,
    text1: "Queso",
    text2: "Quirófano",
    text3: "Químico",
  },
  {
    id: 18,
    letra: "r",
    image1: imgs.raton,
    image2: imgs.roca,
    image3: imgs.rama,
    text1: "Ratón",
    text2: "Roca",
    text3: "Rama",
  },
  {
    id: 19,
    letra: "s",
    image1: imgs.sapo,
    image2: imgs.sol,
    image3: imgs.silla,
    text1: "Sapo",
    text2: "Sol",
    text3: "Silla",
  },
  {
    id: 20,
    letra: "t",
    image1: imgs.tomate,
    image2: imgs.toro,
    image3: imgs.tortuga,
    text1: "Tomate",
    text2: "Toro",
    text3: "Tortuga",
  },
  {
    id: 21,
    letra: "u",
    image1: imgs.uva,
    image2: imgs.unia,
    image3: imgs.unicornio,
    text1: "Uva",
    text2: "Uña",
    text3: "Unicornio",
  },
  {
    id: 22,
    letra: "v",
    image1: imgs.vaso,
    image2: imgs.vela,
    image3: imgs.vino,
    text1: "Vaso",
    text2: "Vela",
    text3: "Vino",
  },
  {
    id: 23,
    letra: "w",
    image1: imgs.wifi,
    image2: imgs.waffle,
    image3: imgs.walle,
    text1: "Wifi",
    text2: "Waffle",
    text3: "Wall-e",
  },
  {
    id: 24,
    letra: "x",
    image1: imgs.xilofono,
    image2: imgs.xhipo,
    image3: imgs.xilografia,
    text1: "Xilófono",
    text2: "Xhipo",
    text3: "Xilografía",
  },
  {
    id: 25,
    letra: "y",
    image1: imgs.yoyo,
    image2: imgs.yegua,
    image3: imgs.yogur,
    text1: "Yoyo",
    text2: "Yegua",
    text3: "Yogur",
  },
  {
    id: 26,
    letra: "z",
    image1: imgs.zorro,
    image2: imgs.zapallo,
    image3: imgs.zanahoria,
    text1: "Zorro",
    text2: "Zapallo",
    text3: "Zanahoria",
  },
];


export default letras;